version: "2.4"

services:
  proxy:
    build:
      context: ../../

    # image: golang:latest
    command: go run ./example/proxysip -t tcp -ip=10.5.0.10:5060 -dst 10.5.0.20:5060 -debug
    # stdin_open: true
    # command: bash
    # working_dir: /usr/src/sipgo
    volumes:
      - ../../../sipgo:/go/sipgo

    cpus: 4.0
    cpuset: "0,1,2,3"

    networks:
      mynet:
        ipv4_address: 10.5.0.10

    # mem_limit: 4G
    # network_mode: "host"
    environment:
      - GOMAXPROCS=4 # Go does not match this by default
      # - GODEBUG=madvdontneed=0
      # - GODEBUG=madvdontneed=1,gctrace=1
      # - GOGC=70

  uas:
    image: ctaloi/sipp
    command: -sn uas -t tn -i 10.5.0.20:5060 -trace_msg -trace_calldebug -trace_err -trace_logs
    # network_mode: "host"
    cpuset: "4"
    networks:
      mynet:
        ipv4_address: 10.5.0.20

  uac:
    image: ctaloi/sipp
    command: -sn uac -t tn -r 1 -rp 3000 -i 10.5.0.30 10.5.0.10:5060 -trace_msg
    # network_mode: "host"
    cpuset: "5"
    networks:
      mynet:
        ipv4_address: 10.5.0.30
    # depends_on:
    # - proxy
    #  - uas


networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
