version: "2.4"

services:
  proxy:
    image: golang:latest
    command: go run -race ./example/dialog -ip=10.10.0.10:5060 -dst 10.10.0.20:5060 
    working_dir: /usr/src/sipgo
    volumes:
      - ../../../sipgo:/usr/src/sipgo

    networks:
      mynet:
        ipv4_address: 10.10.0.10

  uas:
    image: ctaloi/sipp
    command: -sn uas -i 10.10.0.20
    # network_mode: "host"
    cpuset: "4"
    networks:
      mynet:
        ipv4_address: 10.10.0.20

  uac:
    image: ctaloi/sipp
    command: -sn uac -r 1 -rp 1000 -i 10.10.0.30 10.10.0.10:5060
    # network_mode: "host"
    networks:
      mynet:
        ipv4_address: 10.10.0.30

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
